### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by o-n** [entropia9/FlightSearch#1]
Hey!
Does this app function when you test it??
When I install this app on my phone the input does not function as expected. I tested on Samsung A13 and motorola xt2271-4.

The input cursor is moved one slot back and the letters show up somewhat at random, rarely the ones typed. 

I am working on the same tutorial and the same issue occur when running my own app and was surprised to see same issue show up on your app :-/  I tested another persons app they where using lifecycle with no input issues.

**Comment by entropia9** [comment]
Hi, I somehow didn't fixed it way back when I was doing it, even though I remember working on it.  I updated the project now with the version that works (at least as far as I tested it).
Basically the problem was that copies of input were falling out of sync due to being overwritten asynchronously. I assume it's the same issue in your app, here you can read more about it and the best practice to tackle it: [link](https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5)
Thanks for letting me know about the issue.

**Comment by o-n** [comment]
That makes sense, thank you so much! Happy coding
